import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { asc } from 'drizzle-orm'
import { db, overrides, projects, rules } from '@/db'
import { configDir, ensureDirs } from '@/lib/paths'
import type { JobLogger } from '@/lib/sources/types'

/**
 * Mirror rules, overrides and projects out to YAML on every attribute pass.
 *
 * The database is disposable by design — but your categorisation judgement
 * isn't, and overrides in particular cannot be recreated from any upstream
 * source. Writing them to `config/` (which you should `git init`) means every
 * correction you make gets a diff and a history, and a lost container costs
 * you nothing.
 */

const q = (s: unknown): string => {
  if (s == null) return 'null'
  const str = String(s)
  return /^[A-Za-z0-9_\-./ ]+$/.test(str) && str.trim() === str
    ? str
    : JSON.stringify(str)
}

export async function exportConfig(log: JobLogger = () => {}): Promise<void> {
  ensureDirs()
  const dir = configDir()

  const [ruleRows, ovrRows, projRows] = await Promise.all([
    db.select().from(rules).orderBy(asc(rules.priority)),
    db.select().from(overrides),
    db.select().from(projects).orderBy(asc(projects.sortOrder)),
  ])

  const projYaml = [
    '# Generated by the attribute pass. Safe to edit — imported on next boot.',
    'projects:',
    ...projRows.map((p) =>
      [
        `  - id: ${q(p.id)}`,
        `    name: ${q(p.name)}`,
        `    color: ${q(p.color)}`,
        `    status: ${q(p.status)}`,
      ].join('\n'),
    ),
  ].join('\n')

  const rulesYaml = [
    '# Attribution rules, ascending priority. First match wins per field.',
    'rules:',
    ...ruleRows.map((r) =>
      [
        `  - id: ${q(r.id)}`,
        `    priority: ${r.priority}`,
        `    enabled: ${r.enabled}`,
        `    target: ${q(r.target)}`,
        r.scopeSource ? `    scope_source: ${q(r.scopeSource)}` : null,
        `    match: ${q(r.matchPattern)}`,
        r.minCents != null ? `    min_cents: ${r.minCents}` : null,
        r.maxCents != null ? `    max_cents: ${r.maxCents}` : null,
        r.setProjectId ? `    project: ${q(r.setProjectId)}` : null,
        r.setCategory ? `    category: ${q(r.setCategory)}` : null,
        r.setCostType ? `    cost_type: ${q(r.setCostType)}` : null,
        `    hits: ${r.hits}`,
      ]
        .filter(Boolean)
        .join('\n'),
    ),
  ].join('\n')

  const ovrYaml = [
    '# Human corrections, keyed by stable fingerprint. THE precious file:',
    '# nothing upstream can regenerate these. Keep this directory in git.',
    'overrides:',
    ...ovrRows.map((o) =>
      [
        `  - fingerprint: ${q(o.fingerprint)}`,
        `    scope: ${q(o.scope)}`,
        o.projectId ? `    project: ${q(o.projectId)}` : null,
        o.category ? `    category: ${q(o.category)}` : null,
        o.costType ? `    cost_type: ${q(o.costType)}` : null,
        o.splitPct ? `    split_pct: ${JSON.stringify(o.splitPct)}` : null,
        o.note ? `    note: ${q(o.note)}` : null,
      ]
        .filter(Boolean)
        .join('\n'),
    ),
  ].join('\n')

  await Promise.all([
    writeFile(path.join(dir, 'projects.yaml'), projYaml + '\n', 'utf8'),
    writeFile(path.join(dir, 'rules.yaml'), rulesYaml + '\n', 'utf8'),
    writeFile(path.join(dir, 'overrides.yaml'), ovrYaml + '\n', 'utf8'),
  ])

  log(`exported ${ruleRows.length} rules, ${ovrRows.length} overrides to config/`)
}
